const ages = require("../ages.json");
const ageCost = require("../ages-cost/OceanicFuture");

Object.defineProperty(exports, "__esModule", {
  value: true,
});

exports.default = {
  key: "Atlantis_Museum",
  gbReward: {
    1: {
      plunder_and_pillage: 12,
      random_goods: 10,
      random_goods_afterModern: 20,
      trials: 2,
    },
    2: {
      plunder_and_pillage: 13,
      random_goods: 12,
      random_goods_afterModern: 24,
      trials: 2,
    },
    3: {
      plunder_and_pillage: 14.25,
      random_goods: 14,
      random_goods_afterModern: 28,
      trials: 2,
    },
    4: {
      plunder_and_pillage: 15.4,
      random_goods: 15,
      random_goods_afterModern: 30,
      trials: 2,
    },
    5: {
      plunder_and_pillage: 16.6,
      random_goods: 17,
      random_goods_afterModern: 34,
      trials: 2,
    },
    6: {
      plunder_and_pillage: 17.8,
      random_goods: 19,
      random_goods_afterModern: 38,
      trials: 2,
    },
    7: {
      plunder_and_pillage: 19,
      random_goods: 21,
      random_goods_afterModern: 42,
      trials: 2,
    },
    8: {
      plunder_and_pillage: 20.25,
      random_goods: 22,
      random_goods_afterModern: 44,
      trials: 2,
    },
    9: {
      plunder_and_pillage: 21.5,
      random_goods: 24,
      random_goods_afterModern: 48,
      trials: 2,
    },
    10: {
      plunder_and_pillage: 22.75,
      random_goods: 26,
      random_goods_afterModern: 52,
      trials: 2,
    },
    11: {
      plunder_and_pillage: 23.86,
      random_goods: 27,
      random_goods_afterModern: 54,
      trials: 2,
    },
    12: {
      plunder_and_pillage: 24.24,
      random_goods: 28,
      random_goods_afterModern: 56,
      trials: 2,
    },
    13: {
      plunder_and_pillage: 24.62,
      random_goods: 29,
      random_goods_afterModern: 58,
      trials: 2,
    },
    14: {
      plunder_and_pillage: 25,
      random_goods: 30,
      random_goods_afterModern: 60,
      trials: 2,
    },
    15: {
      plunder_and_pillage: 25.38,
      random_goods: 31,
      random_goods_afterModern: 62,
      trials: 2,
    },
    16: {
      plunder_and_pillage: 25.76,
      random_goods: 32,
      random_goods_afterModern: 64,
      trials: 2,
    },
    17: {
      plunder_and_pillage: 26.14,
      random_goods: 33,
      random_goods_afterModern: 66,
      trials: 2,
    },
    18: {
      plunder_and_pillage: 26.51,
      random_goods: 34,
      random_goods_afterModern: 68,
      trials: 2,
    },
    19: {
      plunder_and_pillage: 26.89,
      random_goods: 35,
      random_goods_afterModern: 70,
      trials: 2,
    },
    20: {
      plunder_and_pillage: 27.27,
      random_goods: 36,
      random_goods_afterModern: 72,
      trials: 2,
    },
    21: {
      plunder_and_pillage: 27.64,
      random_goods: 37,
      random_goods_afterModern: 74,
      trials: 2,
    },
    22: {
      plunder_and_pillage: 28.02,
      random_goods: 38,
      random_goods_afterModern: 76,
      trials: 2,
    },
    23: {
      plunder_and_pillage: 28.39,
      random_goods: 39,
      random_goods_afterModern: 78,
      trials: 2,
    },
    24: {
      plunder_and_pillage: 28.76,
      random_goods: 40,
      random_goods_afterModern: 80,
      trials: 2,
    },
    25: {
      plunder_and_pillage: 29.13,
      random_goods: 41,
      random_goods_afterModern: 82,
      trials: 2,
    },
    26: {
      plunder_and_pillage: 29.5,
      random_goods: 42,
      random_goods_afterModern: 84,
      trials: 2,
    },
    27: {
      plunder_and_pillage: 29.86,
      random_goods: 43,
      random_goods_afterModern: 86,
      trials: 2,
    },
    28: {
      plunder_and_pillage: 30.22,
      random_goods: 44,
      random_goods_afterModern: 88,
      trials: 2,
    },
    29: {
      plunder_and_pillage: 30.59,
      random_goods: 45,
      random_goods_afterModern: 90,
      trials: 2,
    },
    30: {
      plunder_and_pillage: 30.94,
      random_goods: 46,
      random_goods_afterModern: 92,
      trials: 2,
    },
    31: {
      plunder_and_pillage: 31.3,
      random_goods: 47,
      random_goods_afterModern: 94,
      trials: 2,
    },
    32: {
      plunder_and_pillage: 31.65,
      random_goods: 48,
      random_goods_afterModern: 96,
      trials: 2,
    },
    33: {
      plunder_and_pillage: 32,
      random_goods: 49,
      random_goods_afterModern: 98,
      trials: 2,
    },
    34: {
      plunder_and_pillage: 32.35,
      random_goods: 50,
      random_goods_afterModern: 100,
      trials: 2,
    },
    35: {
      plunder_and_pillage: 32.7,
      random_goods: 51,
      random_goods_afterModern: 102,
      trials: 2,
    },
    36: {
      plunder_and_pillage: 33.04,
      random_goods: 52,
      random_goods_afterModern: 104,
      trials: 2,
    },
    37: {
      plunder_and_pillage: 33.38,
      random_goods: 53,
      random_goods_afterModern: 106,
      trials: 2,
    },
    38: {
      plunder_and_pillage: 33.71,
      random_goods: 54,
      random_goods_afterModern: 108,
      trials: 2,
    },
    39: {
      plunder_and_pillage: 34.04,
      random_goods: 55,
      random_goods_afterModern: 110,
      trials: 2,
    },
    40: {
      plunder_and_pillage: 34.37,
      random_goods: 56,
      random_goods_afterModern: 112,
      trials: 2,
    },
    41: {
      plunder_and_pillage: 34.69,
      random_goods: 57,
      random_goods_afterModern: 114,
      trials: 2,
    },
    42: {
      plunder_and_pillage: 35.01,
      random_goods: 58,
      random_goods_afterModern: 116,
      trials: 2,
    },
    43: {
      plunder_and_pillage: 35.33,
      random_goods: 59,
      random_goods_afterModern: 118,
      trials: 2,
    },
    44: {
      plunder_and_pillage: 35.64,
      random_goods: 60,
      random_goods_afterModern: 120,
      trials: 2,
    },
    45: {
      plunder_and_pillage: 35.95,
      random_goods: 61,
      random_goods_afterModern: 122,
      trials: 2,
    },
    46: {
      plunder_and_pillage: 36.25,
      random_goods: 62,
      random_goods_afterModern: 124,
      trials: 2,
    },
    47: {
      plunder_and_pillage: 36.55,
      random_goods: 63,
      random_goods_afterModern: 126,
      trials: 2,
    },
    48: {
      plunder_and_pillage: 36.85,
      random_goods: 64,
      random_goods_afterModern: 128,
      trials: 2,
    },
    49: {
      plunder_and_pillage: 37.14,
      random_goods: 65,
      random_goods_afterModern: 130,
      trials: 2,
    },
    50: {
      plunder_and_pillage: 37.43,
      random_goods: 66,
      random_goods_afterModern: 132,
      trials: 2,
    },
    51: {
      plunder_and_pillage: 37.71,
      random_goods: 67,
      random_goods_afterModern: 134,
      trials: 2,
    },
    52: {
      plunder_and_pillage: 37.99,
      random_goods: 68,
      random_goods_afterModern: 136,
      trials: 2,
    },
    53: {
      plunder_and_pillage: 38.26,
      random_goods: 69,
      random_goods_afterModern: 138,
      trials: 2,
    },
    54: {
      plunder_and_pillage: 38.53,
      random_goods: 70,
      random_goods_afterModern: 140,
      trials: 2,
    },
    55: {
      plunder_and_pillage: 38.8,
      random_goods: 71,
      random_goods_afterModern: 142,
      trials: 2,
    },
    56: {
      plunder_and_pillage: 39.06,
      random_goods: 72,
      random_goods_afterModern: 144,
      trials: 2,
    },
    57: {
      plunder_and_pillage: 39.32,
      random_goods: 73,
      random_goods_afterModern: 146,
      trials: 2,
    },
    58: {
      plunder_and_pillage: 39.57,
      random_goods: 74,
      random_goods_afterModern: 148,
      trials: 2,
    },
    59: {
      plunder_and_pillage: 39.82,
      random_goods: 75,
      random_goods_afterModern: 150,
      trials: 2,
    },
    60: {
      plunder_and_pillage: 40.06,
      random_goods: 76,
      random_goods_afterModern: 152,
      trials: 2,
    },
    61: {
      plunder_and_pillage: 40.3,
      random_goods: 77,
      random_goods_afterModern: 154,
      trials: 2,
    },
    62: {
      plunder_and_pillage: 40.53,
      random_goods: 78,
      random_goods_afterModern: 156,
      trials: 2,
    },
    63: {
      plunder_and_pillage: 40.77,
      random_goods: 79,
      random_goods_afterModern: 158,
      trials: 2,
    },
    64: {
      plunder_and_pillage: 40.99,
      random_goods: 80,
      random_goods_afterModern: 160,
      trials: 2,
    },
    65: {
      plunder_and_pillage: 41.21,
      random_goods: 81,
      random_goods_afterModern: 162,
      trials: 2,
    },
    66: {
      plunder_and_pillage: 41.43,
      random_goods: 82,
      random_goods_afterModern: 164,
      trials: 2,
    },
    67: {
      plunder_and_pillage: 41.64,
      random_goods: 83,
      random_goods_afterModern: 166,
      trials: 2,
    },
    68: {
      plunder_and_pillage: 41.85,
      random_goods: 84,
      random_goods_afterModern: 168,
      trials: 2,
    },
    69: {
      plunder_and_pillage: 42.06,
      random_goods: 85,
      random_goods_afterModern: 170,
      trials: 2,
    },
    70: {
      plunder_and_pillage: 42.26,
      random_goods: 86,
      random_goods_afterModern: 172,
      trials: 2,
    },
    71: {
      plunder_and_pillage: 42.45,
      random_goods: 87,
      random_goods_afterModern: 174,
      trials: 2,
    },
    72: {
      plunder_and_pillage: 42.65,
      random_goods: 88,
      random_goods_afterModern: 176,
      trials: 2,
    },
    73: {
      plunder_and_pillage: 42.83,
      random_goods: 89,
      random_goods_afterModern: 178,
      trials: 2,
    },
    74: {
      plunder_and_pillage: 43.02,
      random_goods: 90,
      random_goods_afterModern: 180,
      trials: 2,
    },
    75: {
      plunder_and_pillage: 43.2,
      random_goods: 91,
      random_goods_afterModern: 182,
      trials: 2,
    },
    76: {
      plunder_and_pillage: 43.37,
      random_goods: 92,
      random_goods_afterModern: 184,
      trials: 2,
    },
    77: {
      plunder_and_pillage: 43.55,
      random_goods: 93,
      random_goods_afterModern: 186,
      trials: 2,
    },
    78: {
      plunder_and_pillage: 43.71,
      random_goods: 94,
      random_goods_afterModern: 188,
      trials: 2,
    },
    79: {
      plunder_and_pillage: 43.88,
      random_goods: 95,
      random_goods_afterModern: 190,
      trials: 2,
    },
    80: {
      plunder_and_pillage: 44.04,
      random_goods: 96,
      random_goods_afterModern: 192,
      trials: 2,
    },
    81: {
      plunder_and_pillage: 44.2,
      random_goods: 97,
      random_goods_afterModern: 194,
      trials: 2,
    },
    82: {
      plunder_and_pillage: 44.35,
      random_goods: 98,
      random_goods_afterModern: 196,
      trials: 2,
    },
    83: {
      plunder_and_pillage: 44.5,
      random_goods: 99,
      random_goods_afterModern: 198,
      trials: 2,
    },
    84: {
      plunder_and_pillage: 44.65,
      random_goods: 100,
      random_goods_afterModern: 200,
      trials: 2,
    },
    85: {
      plunder_and_pillage: 44.79,
      random_goods: 101,
      random_goods_afterModern: 202,
      trials: 2,
    },
    86: {
      plunder_and_pillage: 44.93,
      random_goods: 102,
      random_goods_afterModern: 204,
      trials: 2,
    },
    87: {
      plunder_and_pillage: 45.07,
      random_goods: 103,
      random_goods_afterModern: 206,
      trials: 2,
    },
    88: {
      plunder_and_pillage: 45.2,
      random_goods: 104,
      random_goods_afterModern: 208,
      trials: 2,
    },
    89: {
      plunder_and_pillage: 45.33,
      random_goods: 105,
      random_goods_afterModern: 210,
      trials: 2,
    },
    90: {
      plunder_and_pillage: 45.46,
      random_goods: 106,
      random_goods_afterModern: 212,
      trials: 2,
    },
    91: {
      plunder_and_pillage: 45.58,
      random_goods: 107,
      random_goods_afterModern: 214,
      trials: 2,
    },
    92: {
      plunder_and_pillage: 45.7,
      random_goods: 108,
      random_goods_afterModern: 216,
      trials: 2,
    },
    93: {
      plunder_and_pillage: 45.82,
      random_goods: 109,
      random_goods_afterModern: 218,
      trials: 2,
    },
    94: {
      plunder_and_pillage: 45.93,
      random_goods: 110,
      random_goods_afterModern: 220,
      trials: 2,
    },
    95: {
      plunder_and_pillage: 46.04,
      random_goods: 111,
      random_goods_afterModern: 222,
      trials: 2,
    },
    96: {
      plunder_and_pillage: 46.15,
      random_goods: 112,
      random_goods_afterModern: 224,
      trials: 2,
    },
    97: {
      plunder_and_pillage: 46.26,
      random_goods: 113,
      random_goods_afterModern: 226,
      trials: 2,
    },
    98: {
      plunder_and_pillage: 46.36,
      random_goods: 114,
      random_goods_afterModern: 228,
      trials: 2,
    },
    99: {
      plunder_and_pillage: 46.46,
      random_goods: 115,
      random_goods_afterModern: 230,
      trials: 2,
    },
    100: {
      plunder_and_pillage: 46.56,
      random_goods: 116,
      random_goods_afterModern: 232,
      trials: 2,
    },
    101: {
      plunder_and_pillage: 46.66,
      random_goods: 117,
      random_goods_afterModern: 234,
      trials: 2,
    },
    102: {
      plunder_and_pillage: 46.75,
      random_goods: 118,
      random_goods_afterModern: 236,
      trials: 2,
    },
    103: {
      plunder_and_pillage: 46.84,
      random_goods: 119,
      random_goods_afterModern: 238,
      trials: 2,
    },
  },
  buildCost: {
    artificial_scales: 425,
    biolight: 475,
    corals: 425,
    pearls: 450,
    plankton: 375,
  },
  age: ages.OceanicFuture.key,
  size: { length: 6, width: 7 },
  levels: ageCost,
};
