const ages = require("../ages.json");
const ageCost = require("../ages-cost/IronAge");

Object.defineProperty(exports, "__esModule", {
  value: true,
});

exports.default = {
  key: "Lighthouse_of_Alexandria",
  gbReward: {
    1: {
      supplies_boost: 60,
      random_goods: 8,
      random_goods_afterModern: 16,
      trials: 40,
    },
    2: {
      supplies_boost: 65,
      random_goods: 9,
      random_goods_afterModern: 18,
      trials: 40,
    },
    3: {
      supplies_boost: 75,
      random_goods: 10,
      random_goods_afterModern: 20,
      trials: 40,
    },
    4: {
      supplies_boost: 85,
      random_goods: 12,
      random_goods_afterModern: 24,
      trials: 40,
    },
    5: {
      supplies_boost: 95,
      random_goods: 13,
      random_goods_afterModern: 26,
      trials: 40,
    },
    6: {
      supplies_boost: 105,
      random_goods: 14,
      random_goods_afterModern: 28,
      trials: 40,
    },
    7: {
      supplies_boost: 115,
      random_goods: 15,
      random_goods_afterModern: 30,
      trials: 40,
    },
    8: {
      supplies_boost: 125,
      random_goods: 34,
      random_goods_afterModern: 68,
      trials: 40,
    },
    9: {
      supplies_boost: 135,
      random_goods: 18,
      random_goods_afterModern: 36,
      trials: 40,
    },
    10: {
      supplies_boost: 145,
      random_goods: 19,
      random_goods_afterModern: 38,
      trials: 40,
    },
    11: {
      supplies_boost: 150,
      random_goods: 20,
      random_goods_afterModern: 40,
      trials: 40,
    },
    12: {
      supplies_boost: 155,
      random_goods: 21,
      random_goods_afterModern: 42,
      trials: 40,
    },
    13: {
      supplies_boost: 160,
      random_goods: 22,
      random_goods_afterModern: 44,
      trials: 40,
    },
    14: {
      supplies_boost: 165,
      random_goods: 23,
      random_goods_afterModern: 46,
      trials: 40,
    },
    15: {
      supplies_boost: 170,
      random_goods: 24,
      random_goods_afterModern: 48,
      trials: 40,
    },
    16: {
      supplies_boost: 175,
      random_goods: 25,
      random_goods_afterModern: 50,
      trials: 40,
    },
    17: {
      supplies_boost: 180,
      random_goods: 26,
      random_goods_afterModern: 52,
      trials: 40,
    },
    18: {
      supplies_boost: 185,
      random_goods: 27,
      random_goods_afterModern: 54,
      trials: 40,
    },
    19: {
      supplies_boost: 190,
      random_goods: 28,
      random_goods_afterModern: 56,
      trials: 40,
    },
    20: {
      supplies_boost: 195,
      random_goods: 29,
      random_goods_afterModern: 58,
      trials: 40,
    },
    21: {
      supplies_boost: 200,
      random_goods: 30,
      random_goods_afterModern: 60,
      trials: 40,
    },
    22: {
      supplies_boost: 205,
      random_goods: 31,
      random_goods_afterModern: 62,
      trials: 40,
    },
    23: {
      supplies_boost: 210,
      random_goods: 32,
      random_goods_afterModern: 64,
      trials: 40,
    },
    24: {
      supplies_boost: 215,
      random_goods: 66,
      random_goods_afterModern: 132,
      trials: 40,
    },
    25: {
      supplies_boost: 220,
      random_goods: 34,
      random_goods_afterModern: 68,
      trials: 40,
    },
    26: {
      supplies_boost: 225,
      random_goods: 35,
      random_goods_afterModern: 70,
      trials: 40,
    },
    27: {
      supplies_boost: 230,
      random_goods: 36,
      random_goods_afterModern: 72,
      trials: 40,
    },
    28: {
      supplies_boost: 235,
      random_goods: 37,
      random_goods_afterModern: 74,
      trials: 40,
    },
    29: {
      supplies_boost: 240,
      random_goods: 38,
      random_goods_afterModern: 76,
      trials: 40,
    },
    30: {
      supplies_boost: 245,
      random_goods: 39,
      random_goods_afterModern: 78,
      trials: 40,
    },
    31: {
      supplies_boost: 250,
      random_goods: 40,
      random_goods_afterModern: 80,
      trials: 40,
    },
    32: {
      supplies_boost: 255,
      random_goods: 41,
      random_goods_afterModern: 82,
      trials: 40,
    },
    33: {
      supplies_boost: 260,
      random_goods: 42,
      random_goods_afterModern: 84,
      trials: 40,
    },
    34: {
      supplies_boost: 265,
      random_goods: 43,
      random_goods_afterModern: 86,
      trials: 40,
    },
    35: {
      supplies_boost: 270,
      random_goods: 44,
      random_goods_afterModern: 88,
      trials: 40,
    },
    36: {
      supplies_boost: 275,
      random_goods: 45,
      random_goods_afterModern: 90,
      trials: 40,
    },
    37: {
      supplies_boost: 280,
      random_goods: 46,
      random_goods_afterModern: 92,
      trials: 40,
    },
    38: {
      supplies_boost: 285,
      random_goods: 47,
      random_goods_afterModern: 94,
      trials: 40,
    },
    39: {
      supplies_boost: 290,
      random_goods: 48,
      random_goods_afterModern: 96,
      trials: 40,
    },
    40: {
      supplies_boost: 295,
      random_goods: 49,
      random_goods_afterModern: 98,
      trials: 40,
    },
    41: {
      supplies_boost: 300,
      random_goods: 50,
      random_goods_afterModern: 100,
      trials: 40,
    },
    42: {
      supplies_boost: 305,
      random_goods: 51,
      random_goods_afterModern: 102,
      trials: 40,
    },
    43: {
      supplies_boost: 310,
      random_goods: 52,
      random_goods_afterModern: 104,
      trials: 40,
    },
    44: {
      supplies_boost: 315,
      random_goods: 53,
      random_goods_afterModern: 106,
      trials: 40,
    },
    45: {
      supplies_boost: 320,
      random_goods: 54,
      random_goods_afterModern: 108,
      trials: 40,
    },
    46: {
      supplies_boost: 325,
      random_goods: 55,
      random_goods_afterModern: 110,
      trials: 40,
    },
    47: {
      supplies_boost: 330,
      random_goods: 56,
      random_goods_afterModern: 112,
      trials: 40,
    },
    48: {
      supplies_boost: 335,
      random_goods: 57,
      random_goods_afterModern: 114,
      trials: 40,
    },
    49: {
      supplies_boost: 340,
      random_goods: 58,
      random_goods_afterModern: 116,
      trials: 40,
    },
    50: {
      supplies_boost: 345,
      random_goods: 59,
      random_goods_afterModern: 118,
      trials: 40,
    },
    51: {
      supplies_boost: 350,
      random_goods: 60,
      random_goods_afterModern: 120,
      trials: 40,
    },
    52: {
      supplies_boost: 355,
      random_goods: 61,
      random_goods_afterModern: 122,
      trials: 40,
    },
    53: {
      supplies_boost: 360,
      random_goods: 62,
      random_goods_afterModern: 124,
      trials: 40,
    },
    54: {
      supplies_boost: 365,
      random_goods: 63,
      random_goods_afterModern: 126,
      trials: 40,
    },
    55: {
      supplies_boost: 370,
      random_goods: 64,
      random_goods_afterModern: 128,
      trials: 40,
    },
    56: {
      supplies_boost: 375,
      random_goods: 65,
      random_goods_afterModern: 130,
      trials: 40,
    },
    57: {
      supplies_boost: 380,
      random_goods: 66,
      random_goods_afterModern: 132,
      trials: 40,
    },
    58: {
      supplies_boost: 385,
      random_goods: 67,
      random_goods_afterModern: 134,
      trials: 40,
    },
    59: {
      supplies_boost: 390,
      random_goods: 68,
      random_goods_afterModern: 136,
      trials: 40,
    },
    60: {
      supplies_boost: 395,
      random_goods: 69,
      random_goods_afterModern: 138,
      trials: 40,
    },
    61: {
      supplies_boost: 400,
      random_goods: 70,
      random_goods_afterModern: 140,
      trials: 40,
    },
    62: {
      supplies_boost: 405,
      random_goods: 71,
      random_goods_afterModern: 142,
      trials: 40,
    },
    63: {
      supplies_boost: 410,
      random_goods: 72,
      random_goods_afterModern: 144,
      trials: 40,
    },
    64: {
      supplies_boost: 415,
      random_goods: 73,
      random_goods_afterModern: 146,
      trials: 40,
    },
    65: {
      supplies_boost: 420,
      random_goods: 74,
      random_goods_afterModern: 148,
      trials: 40,
    },
    66: {
      supplies_boost: 425,
      random_goods: 75,
      random_goods_afterModern: 150,
      trials: 40,
    },
    67: {
      supplies_boost: 430,
      random_goods: 76,
      random_goods_afterModern: 152,
      trials: 40,
    },
    68: {
      supplies_boost: 435,
      random_goods: 77,
      random_goods_afterModern: 154,
      trials: 40,
    },
    69: {
      supplies_boost: 440,
      random_goods: 78,
      random_goods_afterModern: 156,
      trials: 40,
    },
    70: {
      supplies_boost: 445,
      random_goods: 79,
      random_goods_afterModern: 158,
      trials: 40,
    },
    71: {
      supplies_boost: 450,
      random_goods: 80,
      random_goods_afterModern: 160,
      trials: 40,
    },
    72: {
      supplies_boost: 455,
      random_goods: 81,
      random_goods_afterModern: 162,
      trials: 40,
    },
    73: {
      supplies_boost: 460,
      random_goods: 82,
      random_goods_afterModern: 164,
      trials: 40,
    },
    74: {
      supplies_boost: 465,
      random_goods: 83,
      random_goods_afterModern: 166,
      trials: 40,
    },
    75: {
      supplies_boost: 470,
      random_goods: 84,
      random_goods_afterModern: 168,
      trials: 40,
    },
    76: {
      supplies_boost: 475,
      random_goods: 85,
      random_goods_afterModern: 170,
      trials: 40,
    },
    77: {
      supplies_boost: 480,
      random_goods: 86,
      random_goods_afterModern: 172,
      trials: 40,
    },
    78: {
      supplies_boost: 485,
      random_goods: 87,
      random_goods_afterModern: 174,
      trials: 40,
    },
    79: {
      supplies_boost: 490,
      random_goods: 88,
      random_goods_afterModern: 176,
      trials: 40,
    },
    80: {
      supplies_boost: 495,
      random_goods: 89,
      random_goods_afterModern: 178,
      trials: 40,
    },
    81: {
      supplies_boost: 500,
      random_goods: 90,
      random_goods_afterModern: 180,
      trials: 40,
    },
    82: {
      supplies_boost: 505,
      random_goods: 91,
      random_goods_afterModern: 182,
      trials: 40,
    },
    83: {
      supplies_boost: 510,
      random_goods: 92,
      random_goods_afterModern: 184,
      trials: 40,
    },
    84: {
      supplies_boost: 515,
      random_goods: 93,
      random_goods_afterModern: 186,
      trials: 40,
    },
    85: {
      supplies_boost: 520,
      random_goods: 94,
      random_goods_afterModern: 188,
      trials: 40,
    },
    86: {
      supplies_boost: 525,
      random_goods: 95,
      random_goods_afterModern: 190,
      trials: 40,
    },
    87: {
      supplies_boost: 530,
      random_goods: 96,
      random_goods_afterModern: 192,
      trials: 40,
    },
    88: {
      supplies_boost: 535,
      random_goods: 97,
      random_goods_afterModern: 194,
      trials: 40,
    },
    89: {
      supplies_boost: 540,
      random_goods: 98,
      random_goods_afterModern: 196,
      trials: 40,
    },
    90: {
      supplies_boost: 545,
      random_goods: 99,
      random_goods_afterModern: 198,
      trials: 40,
    },
    91: {
      supplies_boost: 550,
      random_goods: 100,
      random_goods_afterModern: 200,
      trials: 40,
    },
    92: {
      supplies_boost: 555,
      random_goods: 101,
      random_goods_afterModern: 202,
      trials: 40,
    },
    93: {
      supplies_boost: 560,
      random_goods: 102,
      random_goods_afterModern: 204,
      trials: 40,
    },
    94: {
      supplies_boost: 565,
      random_goods: 103,
      random_goods_afterModern: 206,
      trials: 40,
    },
    95: {
      supplies_boost: 570,
      random_goods: 104,
      random_goods_afterModern: 208,
      trials: 40,
    },
    96: {
      supplies_boost: 575,
      random_goods: 105,
      random_goods_afterModern: 210,
      trials: 40,
    },
    97: {
      supplies_boost: 580,
      random_goods: 106,
      random_goods_afterModern: 212,
      trials: 40,
    },
    98: {
      supplies_boost: 585,
      random_goods: 107,
      random_goods_afterModern: 214,
      trials: 40,
    },
    99: {
      supplies_boost: 590,
      random_goods: 216,
      random_goods_afterModern: 432,
      trials: 40,
    },
    100: {
      supplies_boost: 595,
      random_goods: 109,
      random_goods_afterModern: 218,
      trials: 40,
    },
    101: {
      supplies_boost: 600,
      random_goods: 110,
      random_goods_afterModern: 220,
      trials: 40,
    },
    102: {
      supplies_boost: 605,
      random_goods: 111,
      random_goods_afterModern: 222,
      trials: 40,
    },
    103: {
      supplies_boost: 610,
      random_goods: 112,
      random_goods_afterModern: 224,
      trials: 40,
    },
    104: {
      supplies_boost: 615,
      random_goods: 113,
      random_goods_afterModern: 226,
      trials: 40,
    },
    105: {
      supplies_boost: 620,
      random_goods: 114,
      random_goods_afterModern: 228,
      trials: 40,
    },
    106: {
      supplies_boost: 625,
      random_goods: 115,
      random_goods_afterModern: 230,
      trials: 40,
    },
    107: {
      supplies_boost: 630,
      random_goods: 116,
      random_goods_afterModern: 232,
      trials: 40,
    },
    108: {
      supplies_boost: 635,
      random_goods: 117,
      random_goods_afterModern: 234,
      trials: 40,
    },
    109: {
      supplies_boost: 640,
      random_goods: 118,
      random_goods_afterModern: 236,
      trials: 40,
    },
    110: {
      supplies_boost: 645,
      random_goods: 119,
      random_goods_afterModern: 238,
      trials: 40,
    },
    111: {
      supplies_boost: 650,
      random_goods: 120,
      random_goods_afterModern: 240,
      trials: 40,
    },
    112: {
      supplies_boost: 655,
      random_goods: 121,
      random_goods_afterModern: 242,
      trials: 40,
    },
    113: {
      supplies_boost: 660,
      random_goods: 122,
      random_goods_afterModern: 244,
      trials: 40,
    },
    114: {
      supplies_boost: 665,
      random_goods: 123,
      random_goods_afterModern: 246,
      trials: 40,
    },
  },
  buildCost: {
    cloth: 70,
    ebony: 60,
    iron: 50,
    jewelry: 80,
    limestone: 40,
  },
  age: ages.IronAge.key,
  size: { length: 4, width: 4 },
  levels: ageCost,
};
